services:
  # Database
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  # Backend API
  server:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # Syncs your code updates live
      - /app/node_modules # Prevents local node_modules from overwriting Docker's
    depends_on:
      - mongo

  # Frontend React
  client:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app # Syncs your code updates live
      - /app/node_modules # Keeps Docker dependencies safe
    environment:
      - CHOKIDAR_USEPOLLING=true # Fixes hot-reload on Windows/WSL
    depends_on:
      - server

volumes:
  mongo-data:
